### ISSUE TITLE
Window manager is not started at session start

### ISSUE THREAD

**Issue by endi123** [mate-desktop/mate-session-manager#21]
MATE worked flawlessly for some time. But after a few weeks of usage, it started to forget to start the WM at MATE start. Sometimes it started, sometimes did not.

I tried everything, configure with dconf-editor and mateconf-editor, nothing helped. It seems this bug exists in GNOME2 too, I found similar issues reported even from 2008. The suggested "solution" on the forums was to start the WM from the autostart directory ("Startup applications" app).

Because MATE worked well for the first few weeks, it was clear that something in the config files went wrong. I removed everything from my home directory, logged out and in, and the WM started! I moved back the old config directories one by one, tested again and again. It turned out that a "marco.desktop" file in ~/.local/share/... caused the problem. Similarly, metacity wont be started at session start if there is a "metacity.desktop" somewhere.

I think this is a serious bug, because renders the system particularly useless for simple users.

**Comment by AKSoo** [comment]
After a full day of frustration with marco not starting with MATE, I finally found the reason here. As @endi123 says, this issue **IS** a MATE problem considering how the DE becomes almost unusable because of a reason that's so difficult to track down. Ignoring this issue seems very irresponsible.

To add more details, the culprit here is the `Hidden=true` at the end of ~/.local/share/applications/marco.desktop . This line gets added when the user deletes marco from a panel's Menu editor (under *Applications/Other* category). This innocuous act of customizing the Menu causes the entire DE to fail ungracefully.

**Comment by lukefromdc** [comment]
This is further complicated by the fact that marco should NOT start when another window manager such as compiz is being started by the session. 

That` Hidden=true`  must be added when mate-tweak or dconf-editor is used to set org>mate>desktop>session>required-components>windowmanager to something other than marco such as compiz as I have this in my ~/.local/share/applications/marco.desktop although I have never used the menu editor or the startup applications functions in mate-control-center to manually modify this file or remove marco from the list of startup applications.

Thus, the session would need to ensure that some other WM is running or about to start before acting on the Hidden=true in this desktop file. Alternately Hidden-true could be replaced with a startup delay. That would cause marco to error out (though this might be logged) if another WM is running since marco --replace would not be called, but would give compiz (probably the slowest starter we would encounter except when someone starts gnome-shell or cinnamon from a MATE session) time to start.

This might be complex enough to make the most reasonable fix be to document it (option 3) in some way that users would always see in this case.

**Comment by AKSoo** [comment]
I agree that this should be documented, and the user should be directed to the documentation.

How about the origin of the problem, menu editor Mozo? Why is `Hidden=true` used for both Menu items and choosing window manager. Seems to me like a textbook example of bad design.

**Comment by raveit65** [comment]
Why did you edit this entry with mozo?
There isn't any reason to do that and to touch the whole menu point (others) with mozo.
You don't see those menu entries in normal fresh installation because there are not visible in menus.
So again, why did you delete it?
IHMO, mozo is a tool for advanced users.

**Comment by AKSoo** [comment]
[Mozo](https://github.com/mate-desktop/mozo) claims to be a menu editor and nothing more. How is that supposed to a tool for advanced users? In fact, for Debian, it is described as ['Mozo is an easy-to-use menu editor for MATE'](https://packages.debian.org/jessie/utils/mozo).

Any unsuspecting user may delete items they don't need from Mozo while customizing the panel menu. This happens to include Marco, which happens to completely disable it from starting without warning.

I agree that there is no reason to mess with Mozo at all. It is a non-essential customization tool. But that is a terrible argument to dismiss this problem.

&nbsp;
Back on topic, I think the best way to solve this would be using `NoDisplay` or `NotShowIn` desktop entry key when Mozo deletes menu entries. According to [freedesktop specifications](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys), `Hidden` is a misleading key that should have been called Deleted.

I will open an issue on this at mate-desktop/mozo.
